// constants.ts

export const STATUS_OPCOES = [
  'JORNADA', 'FOLGA NA ESTRADA', 'FOLGA EM CASA', 'FÉRIAS', 'ATESTADO',
  'FALTA', 'SUSPENSÃO', 'LICENÇA PATERNIDADE', 'LICENÇA LUTO', 'DESLIGADO', 'AFASTADO'
];

export const STATUS_VIAGEM_OPCOES = [
  'EM VIAGEM', 'EM CARREGAMENTO', 'EM DESCARGA'
];

export const HORA_EXTRA_OPCOES = [
  'AUTORIZADO', 'NÃO AUTORIZADO'
];
